Fix packages.txt for Debian Bookworm (Streamlit Cloud)
Remove libgthread-2.0-0 - this package doesn't exist in Debian Bookworm.
The package was causing apt-get to fail, which prevented all system
dependencies from being installed, resulting in OpenCV import errors.

This fixes the error:
E: Unable to locate package libgthread-2.0-0
ImportError: libGL.so.1: cannot open shared object file